package client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "DummyService", targetNamespace = "http://service/")
public interface DummyService {


    /**
     * @param arg1
     * @param arg0
     *
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://service/", className = "service.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://service/", className = "service.SumResponse")
    @Action(input = "http://service/DummyService/sumRequest", output = "http://service/DummyService/sumResponse")
    public int sum(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                   @WebParam(name = "arg1", targetNamespace = "") int arg1);

}
